""" cp ./vimrc $HOME/.vimrc

let vimrc_ch = 1024
let vimrc_en = 512

if vimrc_ch > vimrc_en
    source ~/Documents/GIT_HUB/profiles/vim/my_vimrc/vimrc_ch
else
    source ~/Documents/GIT_HUB/profiles/vim/my_vimrc/vimrc_en
endif

